export const ADD_POST = "ADD-POST";
export const ADD_MESSAGE = "ADD-MESSAGE";
export const POST_TEXT_CHANGE_HANDLER = "POST-TEXT-CHANGE-HANDLER";
export const MESSAGE_TEXT_CHANGE_HANDLER = "MESSAGE-CHANGE-TEXT-HANDLER";
export const TOGGLE_FOLLOW = 'TOGGLE-FOLLOW'
export const SET_FRIENDS = "SET-FRIENDS"